version: '3.8'

services:
  db: 
    image: postgres:14
    restart: always
    container_name: deezer-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=deezer_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django
    command: >
       sh -c 'python manage.py makemigrations --noinput && 
              python manage.py migrate --noinput && 
              python manage.py shell < config.py && 
              python manage.py runserver 0.0.0.0:8000'
    env_file:
      - ./.env.local
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=deezer_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db