# Generated by Django 5.1.1 on 2024-09-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='num_searches',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='songplay',
            name='num_plays',
            field=models.BigIntegerField(default=1),
        ),
    ]
